apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ${copilot-pipeline}
  namespace: copilot-namespace
spec:
  resources:
    - name: source-repo
      type: git
  params:
    - name: repoUrl
      type: string
    - name: isTag
      type: string
    - name: revision
      type: string
    - name: uploadUrl
      type: string
    - name: key
      type: string
  tasks:
    - name: npm-install
      taskRef:
        name: npm-install
      resources:
        inputs:
          - name: workspace
            resource: source-repo
        outputs:
          - name: workspace
            resource: source-repo
      params:
        - name: repoUrl
          value: $(params.repoUrl)
        - name: isTag
          value: $(params.isTag)
        - name: revision
          value: $(params.revision)
        - name: key
          value: $(params.key)
    - name: npm-test
      taskRef:
        name: npm-test
      resources:
        inputs:
          - name: workspace
            resource: source-repo
            from: [npm-install]
      params:
        - name: uploadUrl
          value: $(params.uploadUrl)
    - name: npm-audit
      taskRef:
        name: npm-audit
      resources:
        inputs:
          - name: workspace
            resource: source-repo
            from: [npm-install]
      params:
        - name: uploadUrl
          value: $(params.uploadUrl)
    - name: npm-outdated
      taskRef:
        name: npm-outdated
      resources:
        inputs:
          - name: workspace
            resource: source-repo
            from: [npm-install]
      params:
        - name: uploadUrl
          value: $(params.uploadUrl)
