apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: ${copilot-history}
  name: ${copilot-history}
spec:
  template:
    spec:
      containers:
          - image: gcr.io/kube-test-241304/copilot-analyzer:1.8.0
            name: copilot-analyzer
            imagePullPolicy: Always
            volumeMounts:
              - name: git-source
                mountPath: /workspace
            envFrom:
              - configMapRef:
                  name: ${repoInfo}
            env:
              - name: MONGO_HOST
                value: "mongo"
              - name: MONGO_PORT
                value: "27017"
              - name: WEBHOOK_URL
                value: "http://copilot-api:7001"
              - name: ROOT_PATH
                value: "/workspace"
              - name: SERVER_PORT
                value: "3000"
      initContainers:
        - image: gcr.io/kube-test-241304/copilot-histories:0.5.0
          name: copilot-histories
          imagePullPolicy: Always
          volumeMounts:
            - name: git-source
              mountPath: /workspace
          securityContext:
            runAsUser: 65533 # git-sync user
          envFrom:
            - configMapRef:
                name: ${repoInfo}
          env:
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: WEBHOOK_URL
              value: "http://copilot-api:7001"
            - name: ROOT_PATH
              value: /workspace
            - name: ACCESS_TOKEN
              valueFrom: 
                secretKeyRef:
                  name: ${secret-name}
                  key: accessToken
      volumes:
        - name: git-source
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
  completions: 1
