apiVersion: batch/v1
kind: Job
metadata:
  labels:
    name: ${copilot-audit}
  name: ${copilot-audit}
spec:
  template:
    spec:
      containers:
        - image: gcr.io/metatype-dev/copilot-audit:0.9.0
          name: copilot-audit
          imagePullPolicy: Always
          volumeMounts:
            - name: audit-source
              mountPath: /workspace
          envFrom:
            - configMapRef:
                name: ${repoInfo}
          env:
            - name: WEBHOOK_URL
              value: "http://copilot-api:7001"
            - name: ROOT_PATH
              value: "/workspace"
      initContainers:
        - image: gcr.io/metatype-dev/copilot-histories:0.9.0
          name: copilot-histories
          imagePullPolicy: Always
          volumeMounts:
            - name: audit-source
              mountPath: /workspace
          securityContext:
            runAsUser: 65533 # git-sync user
          envFrom:
            - configMapRef:
                name: ${repoInfo}
          env:
            - name: WEBHOOK_URL
              value: "http://copilot-api:7001"
            - name: ROOT_PATH
              value: /workspace
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${secret-name}
                  key: accessToken
      volumes:
        - name: audit-source
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
  completions: 1